sirjCreatPplUIFunc = function() {
    out = list(
      "exptRadio" = radioButtons(inputId = "exptPerson",
                                 label = "Expertise level",
                                 choices = c("1" = 1,
                                             "2" = 2,
                                             "3" = 3,
                                             "4" = 4,
                                             "5" = 5),
                                 selected = pplAtt$attMat$expt[as.numeric(input$person)],
                                 inline = T),
      
      "expLvlRadio" = sliderInput(inputId = "expLvlPerson",
                                  label = "Experience strength",
                                  min = 1, max = 4, value = pplAtt$attMat$expLvl[as.numeric(input$person)], step = 1),      
      "METhrSlider" = sliderInput(inputId = "METhrPerson", 
                                  label = "Threshold for ME response",
                                  min = .2, max = 1, value = pplAtt$attMat$METhr[as.numeric(input$person)], step = .01),
      
      "LEThrSlider" = sliderInput(inputId = "LEThrPerson",
                                  label = "Threshold for LE response",
                                  min = -1, max = -.2, value = pplAtt$attMat$LEThr[as.numeric(input$person)], step = .01),
      
      "AcSlider" = sliderInput(inputId = "AcPerson",
                               label = "Activation level threshold",
                               min = .01, max = 1, value = pplAtt$attMat$Ac[as.numeric(input$person)], step = .01),
      
      "TmaxSlider" = sliderInput(inputId = "TmaxPerson",
                                 label = "Motivation level",
                                 min = 5, max = 10, value = pplAtt$attMat$Tmax[as.numeric(input$person)], step = 1)
      )
  return(out)
}

sirjCreatSJTUIFunc = function() {
  out = list(
    "sitTypeRadio" = radioButtons(inputId = "sitTypeItem",
                                  label = "Broad situation type",
                                  choices = c("1" = 1,
                                              "2" = 2,
                                              "3" = 3),
                                  selected = sjtAtt$attMat$sitType[as.numeric(input$sjtItem)],
                                  inline = T),
    "sitSpecRadio" = radioButtons(inputId = "sitSpecItem",
                                  label = "Specific situation type",
                                  choices = c("1" = 1,
                                              "2" = 2,
                                              "3" = 3,
                                              "4" = 4,
                                              "5" = 5),
                                  selected = sjtAtt$attMat$sitSpec[as.numeric(input$sjtItem)],
                                  inline = T),
    "rspARadio" = radioButtons(inputId = "rspAItem",
                               label = "Expertise Level of Response A",
                               choices = c("1" = 1,
                                           "2" = 2,
                                           "3" = 3,
                                           "4" = 4,
                                           "5" = 5),
                               selected = sjtAtt$attMat$rspA[as.numeric(input$sjtItem)],
                               inline = T),
    "rspBRadio" = radioButtons(inputId = "rspBItem",
                               label = "Expertise Level of Response B",
                               choices = c("1" = 1,
                                           "2" = 2,
                                           "3" = 3,
                                           "4" = 4,
                                           "5" = 5),
                               selected = sjtAtt$attMat$rspB[as.numeric(input$sjtItem)],
                               inline = T),
    "rspCRadio" = radioButtons(inputId = "rspCItem",
                               label = "Expertise Level of Response C",
                               choices = c("1" = 1,
                                           "2" = 2,
                                           "3" = 3,
                                           "4" = 4,
                                           "5" = 5),
                               selected = sjtAtt$attMat$rspC[as.numeric(input$sjtItem)],
                               inline = T),
    "rspDRadio" = radioButtons(inputId = "rspDItem",
                               label = "Expertise Level of Response D",
                               choices = c("1" = 1,
                                           "2" = 2,
                                           "3" = 3,
                                           "4" = 4,
                                           "5" = 5),
                               selected = sjtAtt$attMat$rspD[as.numeric(input$sjtItem)],
                               inline = T)
  )
}